[font]
size = 12.0

[font.bold]
family = "Inconsolata"

[font.bold_italic]
family = "Inconsolata"

[font.italic]
family = "Inconsolata"

[font.normal]
family = "Inconsolata"

[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "Return"
mods = "Alt"
